# Project information
site_name: AQuietOne Docs
site_url: https://aquietone.github.io/aquietone/
site_author: aquietone

# Repository
repo_name: AQuietOne Docs
repo_url: https://github.com/aquietone/aquietone
edit_uri: https://github.com/aquietone/aquietone/edit/master/
docs_dir: .

# Copyright
copyright: Copyright &copy; 2022 aquietone

extra_css:
  - stylesheets/extra.css

# Navigation
nav:

- Home:
  - README.md

  - Getting Started: main/README.md
- BoxHUD:
  - boxhud/README.md
  - Commands: boxhud/commands.md
  - Configuration:
    - General Settings: boxhud/settings.md
    - Properties: boxhud/properties.md
    - Columns: boxhud/columns.md
    - Tabs: boxhud/tabs.md
    - Windows: boxhud/windows.md
  - FAQ: boxhud/faq.md
  - Change Log: https://gitlab.com/aquietone/boxhud/blob/master/CHANGELOG" target="_blank
- MAUI:
  - maui/README.md
  - FAQ: maui/faq.md
  - Change Log: https://gitlab.com/aquietone/maui/blob/main/CHANGELOG" target="_blank
- Event Manager:
  - lem/README.md
  - Commands: lem/commands.md
  - Text Events:
    - Managing Text Events: lem/events/manage.md
    - Text Event Examples: lem/events/examples.md
  - Condition Events:
    - Managing Condition Events: lem/reacts/manage.md
    - Text Condition Examples: lem/reacts/examples.md
  - FAQ: lem/faq.md
  - Change Log: https://gitlab.com/aquietone/event-manager/blob/dev/CHANGELOG" target="_blank
- Chase:
  - chase/README.md
  - FAQ: maui/faq.md
  - Change Log: https://gitlab.com/aquietone/luachase/blob/main/CHANGELOG" target="_blank
- AQOBot:
  - aqobot/README.md
  - Settings: aqobot/settings.md
  - Commands: aqobot/commands.md
  - Classes:
    - Bard: aqobot/classes/brd.md
    - Enchanter: aqobot/classes/enc.md
    - Necromancer: aqobot/classes/nec.md
    - Ranger: aqobot/classes/rng.md
    - Shadow Knight: aqobot/classes/shd.md
    - Warrior: aqobot/classes/war.md
  - FAQ: aqobot/faq.md
  - Change Log: https://gitlab.com/aquietone/aqobot/blob/main/CHANGELOG" target="_blank
- WordQuest:
  - wordquest/README.md
  - Change Log: https://gitlab.com/aquietone/wordquest/blob/main/CHANGELOG" target="_blank
- Misc:
  - misc/README.md
  - Aten Ha Ra Mission Script: misc/atensilence.md
  - Shei Vinitras Mission Script: misc/sheiroot.md
  - ImGui File Dialog: misc/filedialog.md
  - Lua Expression Evaluator: misc/eval.md
  - ImGui Skeleton: misc/uisample.md
  - Lua Timer Library: misc/timer.md
  - Lua Cache Library: misc/cache.md
  - Change Log: https://gitlab.com/aquietone/misclua/blob/main/CHANGELOG" target="_blank

# Theme
theme:
  name: material

  logo: images/logo.png
  favicon: images/logo.png

  font:
    code: Source Code Pro

  features:
    - navigation.tabs
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.indexes
    - navigation.top
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github

# Plugins
plugins:
  - search
  - same-dir
  - redirects
  - tags

# Customization

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - mdx_math
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde