# Project information
site_name: AQuietOne Docs
site_url: https://aquietone.github.io/aquietone/
site_author: aquietone

# Repository
repo_name: AQuietOne Docs
repo_url: https://github.com/aquietone/aquietone
edit_uri: https://github.com/aquietone/aquietone/edit/master/
docs_dir: .

# Copyright
copyright: Copyright &copy; 2022 aquietone

extra_css:
  - stylesheets/extra.css

# Navigation
nav:

- Home:
  - README.md

  - Getting Started: main/README.md
- BoxHUD:
  - boxhud/README.md
  - Change Log: https://gitlab.com/aquietone/boxhud/blob/master/CHANGELOG.md" target="_blank
- MAUI:
  - maui/README.md
  - Change Log: https://gitlab.com/aquietone/maui/blob/main/CHANGELOG.md" target="_blank
- Event Manager:
  - lem/README.md
  - Change Log: https://gitlab.com/aquietone/event-manager/blob/dev/CHANGELOG.md" target="_blank
- Chase:
  - chase/README.md
  - Change Log: https://gitlab.com/aquietone/luachase/blob/main/CHANGELOG.md" target="_blank
- AQOBot:
  - aqobot/README.md
  - Change Log: https://gitlab.com/aquietone/aqobot/blob/main/CHANGELOG.md" target="_blank
- WordQuest:
  - wordquest/README.md
  - Change Log: https://gitlab.com/aquietone/wordquest/blob/main/CHANGELOG.md" target="_blank
- Misc:
  - misc/README.md
  - Change Log: https://gitlab.com/aquietone/misclua/blob/main/CHANGELOG.md" target="_blank

# Theme
theme:
  name: material

  logo: images/logo.png
  favicon: images/logo.png

  font:
    code: Source Code Pro

  features:
    - navigation.tabs
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.indexes
    - navigation.top
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github

# Plugins
plugins:
  - search
  - same-dir
  - redirects
  - tags

# Customization

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - mdx_math
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde